/**
 * **見本の英語の説明。** 名前で引く。
 *
 * ## なぜ別のファイルか
 *
 * 並びと分類の正本は `gallery-categories.mjs`。**そこに 2 言語を混ぜると、
 * どちらの言語を直しているのか読みながら分からなくなる。**
 * ここは「名前 → 英語の 1 行」だけを持つ。
 *
 * **足し忘れは検査が落とす**（`test/gallery-en.test.ts`）——
 * 見本を足して英語を書き忘れると、英語のページにその 1 枚だけ日本語が出る。
 *
 * 日本語の側と**同じことを言わなくてよい。** 読み手が違う ——
 * 「山手線」は向こうでは通じないので "Tokyo's loop line" と書く。
 */

/** 分類の見出し。 */
export const GROUPS_EN = {
  bosai: 'Disaster and emergency',
  manabi: 'Learning and geometry',
  ongaku: 'Instruments and acoustics',
  tetsudo: 'Transit and transport',
  kenchiku: 'Building and civil',
  kaden: 'Appliances and furniture',
  setsubi: 'Services and electrical',
  iryo: 'Health, food and farming',
  tenpo: 'Retail and logistics',
  gyomu: 'Work and organisations',
  moyooshi: 'Events and games',
  ui: 'UI and screen design',
  it: 'IT and software',
};

/**
 * **英語のページだけの分類の順**（2026-09-16）。
 *
 * 並びの正本は `gallery-categories.mjs` だが、そのまま出すと
 * **英語のページが日本の路線図から始まる。** 図の中の文字が日本語のままなので、
 * 初めて見た人はそこで読むのをやめる。英語で書いた見本が多い建築から始め、
 * 日本の鉄道は最後に置く。**見本は 1 枚も落とさない**（数は両方のページで同じ）。
 */
export const ORDER_EN = [
  'kenchiku',
  'bosai',
  'manabi',
  'ongaku',
  'kaden',
  'setsubi',
  'iryo',
  'tenpo',
  'moyooshi',
  'gyomu',
  'ui',
  'it',
  'tetsudo',
];

/**
 * **分類の中では、英字の名前の見本を先に。**
 *
 * 英字の名前は、**図の中も英語で書いた見本**（`140-Exterior-wall-platform-framing`）。
 * 並べ替えは安定 —— 同じ側どうしの順は正本のまま。
 */
export function englishFirst(items) {
  const latin = (item) => !/[\u3040-\u30ff\u4e00-\u9fff]/.test(item.name);
  return [...items.filter(latin), ...items.filter((item) => !latin(item))];
}

/** 名前 → 英語の 1 行。**alt にもこれを使う**（飾りを入れない）。 */
export const CAPTIONS_EN = {
  // 鉄道・交通
  '25-路線図': 'A transit map of six lines told apart by colour and letter code, with interchange stations marked by a double circle rather than by name',
  '78-山手線の路線図': 'The Yamanote loop drawn with its thirty stations evenly spaced rather than to scale, each one carrying the lines you can change to',
  '81-東京の地下鉄13路線': 'Thirteen Tokyo subway lines on one map of the central area, each told apart by its letter code as well as its colour',
  '79-梅田の乗換関係図': 'Seven stations all called Umeda, and the walk between them',
  '80-中央線快速の停車駅一覧': 'Which trains stop where, weekday and weekend',
  '52-停車駅案内図': 'Stopping pattern chart: a band per service, a circle per stop',
  '54-のりかえ案内図': 'Interchange guide with station names set vertically',
  '53-駅時刻表': 'A station timetable with hours down the side and minutes across, weekday and weekend separated, and train types shown by symbol',
  '45-駅の構内図': 'A station on two levels — ground floor and concourse — showing how the gates, stairs, lifts and exits line up with each other',
  '82-多層ターミナルの乗換案内図': 'Interchange across three levels, with the vertical moves',
  '83-駅の配線略図': 'Track layout: two islands, four roads, passing possible',
  '71-列車運行図表': 'A train graph with time across and stations down, where every train becomes a single sloping line and the slope is its speed',
  '111-閉塞と信号現示': 'Block sections and signal aspects, counted back from the train ahead',
  '29-車両の編成図': 'A ten-car commuter train set out car by car: which are motored and which are trailers, where the pantographs are, and what each car carries inside',
  '56-バスの時刻表': 'A bus stop timetable in three columns — weekday, Saturday, Sunday and holiday — with the departure minutes listed under each hour',
  '63-フェリーの発着表': 'Ferry sailings route by route, with departure and arrival times and the name of the vessel working each one',
  '57-登山のコースタイム図': 'A hiking profile with distance across and elevation up, annotated with how long each section takes to walk',
  '334-滑走路の番号とマーキング': 'A runway number is not a name but a bearing: the magnetic heading divided by ten. Use the same strip from the other end and the heading differs by 180 degrees, so the two numbers always differ by 18 and the runway is called 16/34. Because magnetic north drifts, the number painted on the ground is not permanent — when the bearing moves far enough, it gets repainted.',
  '102-ドローンの飛行計画図': 'Drone flight plan and the area kept clear of people',
  '61-道路の平面線形図': 'A road alignment where straights, circular curves and transition curves join up, annotated with chainage and the parameters of each curve',
  '37-配送ルート': 'Delivery rounds for three two-tonne vans: the order of calls, the stops themselves, and the area each van covers',

  // 建築・土木
  '14-間取り': 'A two-bedroom apartment plan with room dimensions, which way each door swings, and where the wet rooms and storage sit',
  '24-校舎の平面図': 'School floor plan (walls, door swings, grid lines, dimensions)',
  '32-ホテルの基準階': 'The typical floor of a business hotel with twelve rooms, the corridor, the fire stairs and the lifts',
  '134-梁の配筋図': 'Beam reinforcement: the last moment it can be changed is before the pour',
  '17-躯体の伏図': 'A reinforced concrete framing plan for a second floor, with the grid lines and the mark of every column, girder, beam and slab',
  '136-天井伏図': 'Reflected ceiling plan: you look up by drawing it looking down',
  '139-矩計図': 'Japanese wall section, where seven heights are fixed at once',
  '140-Exterior-wall-platform-framing': 'Exterior wall framing, in the order a framer builds it',
  '143-Roof-framing-plan': 'Roof framing: in plan a rafter is a line',
  '151-Deck-framing-plan': 'Deck framing: a load path in seven parts',
  '144-Accessible-toilet-room': 'Accessible toilet room: the drawing is made of clearances',
  '141-Two-story-house-plan': 'Two-story house plan in feet and inches, with OPEN TO BELOW',
  '95-避難所レイアウト': 'Shelter layout: 3.5 sq m a person, and how many toilets',
  '22-避難経路図': 'Escape routes on a third floor: two ways out of every room to a staircase, with the travel distance and the fire doors and extinguishers along the way',
  '148-Egress-plan': 'Egress plan: three lengths answering three questions',
  '119-消火器と消火栓の配置図': 'Extinguishers and hose reels, measured two different ways',
  '158-Cattle-handling-facility': 'Every dimension comes from what cattle will not do',
  '172-宮殿の儀礼動線図': 'A palace enfilade: how far down the rooms you are taken IS your rank',
  '171-クロスワードの盤面図': 'A crossword is a grid before it is words: the black squares decide the lengths',
  '170-レゴのモザイク割り付け図': 'A brick mosaic chart: the colour IS the instruction, so every cell also carries a code',
  '169-麻雀の配牌': 'Mahjong: the dice decide where the wall is opened, not luck',
  '168-ダイヤモンドシステム': 'Billiards: the diamonds on the rails are a ruler, not decoration',
  '167-ダーツボードの割り付け': 'A dartboard: the numbers are arranged to punish a miss',
  '260-スライド丁番のかぶせ量': 'You cannot size a cabinet door until the hinge is chosen: the overlay goes straight into the width, and full overlay versus inset differs by 18mm per door',
  '261-電源タップの定格': 'Chaining power strips does not add up: the wall socket caps the whole chain at 15A, the flex gauge caps it lower still (0.75sq means 7A), and the 20A branch breaker trips after the 15A strip has already overheated',
  '262-木工の組み手': 'Dovetail slope is the limit before the corner grain snaps (1:6 in softwood, 1:8 in hardwood), a tenon is one third of the stock, and a 600mm top moves 9mm across the grain — so the joint that fails is usually the one that was not allowed to move',
  '263-加湿器の方式': 'Every humidifier needs the same 627Wh to evaporate a litre — the four types differ only in where that heat comes from, which is why the evaporative one is cheap on the meter and cools the room instead',
  '264-配光曲線と照度計算': 'The lumens on the box describe the fitting, not the desk: a polar candela plot is the only document that connects them, and at 2.5m a spot that gives 400lx underneath gives 110lx just 1.4m to the side',
  '265-建具の開き勝手と有効開口': 'The single arc on a floor plan decides how the room can be used: a 780mm frame only gives 747mm of clear opening once the leaf is in the way, and the door sweeps 0.44m² of floor that nothing else can occupy',
  '266-足関節のテーピング': 'Ankle taping stops one direction only — inversion — and leaves the up-and-down movement alone; the order matters because each strip pins down the ends of the last, so tape that peels is usually tape applied in the wrong order',
  '267-クモの円網': 'A spider does not stick to its own web because only the spiral is sticky: the radials and the temporary scaffold are dry, and the scaffold is cut away as the sticky spiral is laid from the outside in',
  '268-人口ピラミッドの読み方': 'A population pyramid is not a picture of today but eighty years of births stacked upright: the bulges and the notch move up one step every year, and the notch at 1966 records a year people avoided, not a generation that was lost',
  '269-組子の割り付け': 'Kumiko lattice is arithmetic before it is woodwork: fixing the hexagon fixes every length and angle in the pattern, and the three-way joint only lies flat because the three pieces are notched to different depths — one third, two thirds, one half',
  '270-ヘアカットの展開図': 'A haircut diagram records the angle the hair was held at, not the millimetres taken off: 0 degrees gives one length, 90 degrees gives a uniform layer, and everything in between is graduation',
  '271-地籍図': 'A cadastral map is not a drawing but a set of coordinates: the boundary points are held as plane rectangular coordinates, the lines merely join them, and the area falls out of the arithmetic rather than a tape measure',
  '272-空気清浄機の中身': 'The order of the filters is the order of their lifetimes, and the room size on the box is really a time: it names the room this machine can clean in thirty minutes, so a room its own size takes the full half hour',
  '273-洗濯表示の読み方': 'Care labels have only five base shapes — tub, triangle, square, iron, circle — and everything else is a mark added to them; the number is a ceiling, not an instruction, and in 2024 the iron temperatures moved up 10 degrees without the symbols changing',
  '274-特許の手続': 'Japanese patent procedure is a chain of deadlines rather than steps: no examination request within three years and the application is deemed withdrawn, and a granted decision is still not a right until the first three years of fees are paid within thirty days',
  '275-寿司桶の盛付指示図': 'The shape of the vessel decides the arrangement: a round tub is divided radially so every seat sees the same face, while a rectangular plate carries a flowing arrangement because there is only one direction to look from',
  '276-ケーキのデコレーション指示図': 'How many strawberries go on a cake is decided by how many slices it will be cut into, and they sit between the cut lines rather than on them — a berry on the line is halved by the knife and lands on two plates',
  '277-食品トレーサビリティ': 'Each business records only one step back and one step forward; the chain is what makes the whole route traceable, so one missing record breaks it — and the lot size chosen at the factory decides how much has to be recalled',
  '278-ロープ結索の選び方': 'Knots are chosen by the job they do — joining two ropes, tying to an object, or stopping an end — and every knot is the weakest point of the rope, taking it down to 40-80% of its rated strength',
  '279-400mトラックの割り付け': 'Only lane one is 400m, and it is measured 30cm inside the kerb line; every lane outside it is longer by the circumference of one lane width, which is why the staggered starts exist at all',
  '280-墓地の区画図': 'The plot number is not an address but a route — block, section, row, number — because a cemetery keeps adding plots for decades and a flat numbering would have to be redone each time; and what is bought is the right to use, not the land',
  '281-ネイルの指示図': 'Ten nails are not ten copies of one design: a little finger is 6-7mm across where a thumb is 12-16mm, so the same motif simply does not fit, and tip numbers run backwards — the smaller the number, the wider the nail',
  '282-ランドルト環': 'Visual acuity 1.0 is an angle, not a size: the gap must subtend one minute of arc and the whole ring five, which is why a chart for 5m and one for 3m print rings of different sizes',
  '283-中継の決まり': 'Two kinds of handover measured in opposite ways: ekiden fixes a single line and allows hundreds of metres around it to prepare, while a relay fixes a 30m zone and disqualifies anything outside it',
  '335-裁判員が選ばれるまで': 'Six lay judges sit with three professional judges, and a verdict needs more than a majority of the nine: at least one lay judge and at least one professional judge must be among those in favour. So six lay judges agreeing unanimously still decides nothing if no professional judge agrees, and the reverse holds too — it looks like a vote but neither side can move it alone.',
  '284-三審制': 'Three instances does not mean the same three courts: a small civil claim starting at a summary court is appealed to a district court and goes no further than a high court, while a criminal case from the same summary court goes to the high court and then the supreme court',
  '317-オーケストラの配置': 'The strings run left to right from high to low and the louder the instrument the further back it sits, so the seating plan is itself a balance control — and "double wind" or "triple wind" names the size of the orchestra by counting only the woodwind',
  '316-軽減税率の判定': 'The same hamburger is taxed at 8% or 10% depending on a single question at the till, because the line is not drawn around the goods but around whether there are tables and chairs — and a newspaper follows the subscription, not the paper',
  '315-震度とマグニチュード': 'Intensity and magnitude measure different things — one earthquake has a single magnitude but as many intensities as there are places — and because each step of magnitude multiplies the energy by about 32, two steps is already a thousandfold, which is exactly what the small-looking numbers hide',
  '314-うるう年の決め方': 'Ninety-seven leap years every four hundred, not a hundred: dropping three of them brings the average year to 365.2425 days, within 0.0003 of the real one — and the four-hundred-year total happens to divide by seven, so the weekdays come back round as well',
  '313-時計の針の角度': 'At a quarter past three the hands are not together: while the minute hand travelled ninety degrees the hour hand moved seven and a half, and the same arithmetic explains why the hands coincide eleven times in twelve hours rather than twelve',
  '312-UIのComponent構造': 'Draw a component tree per screen and the same component keeps reappearing; the real structure is a net, where one component has several parents — and counting those parents is how you tell a shared component from a screen-specific one before you change it',
  '311-ピアノの鍵盤': 'The black keys are grouped in twos and threes so that a hand can find its place without looking — twelve evenly spaced keys would give no landmark at all — and 88 turns out to be seven octaves plus four: three keys added below and one above',
  '310-ギターのフレット位置': 'Frets crowd together as you climb because what is divided into twelve is not a distance but a ratio: each semitone multiplies by 2^(1/12), so the twelfth fret lands at exactly half the string and everything beyond it repeats at half size',
  '309-電気の引き込み': 'What arrives at a Japanese house is not 100V but a single-phase three-wire 200/100V supply — the two outer conductors are 200V apart and either one is 100V from the neutral — which is why an air conditioner on 200V is not a separate supply but the one that was already there',
  '308-紙のサイズ': 'The whole A series follows from two decisions — A0 has an area of exactly one square metre and the sides are in the ratio root two — and root two is the only ratio that survives being halved, which is also why a photocopier needs just one number to step between sizes',
  '307-乾電池の規格': 'The numbering is not a size order: an AA cell is half a millimetre taller than a C cell, and an N cell is fatter than an AAA — all of them are 1.5 volts, so what a bigger cell buys is current and hours, not strength, and a button cell number like CR2032 is simply its diameter and height in millimetres',
  '306-水が蛇口に届くまで': 'Chlorine goes in twice, and the two doses are for different things: the first, before filtration, is part of the treatment, while the second is there to still be working when the water reaches a tap — and the coagulation stage is two basins, one that stirs fast and one that stirs slowly, because the floc has to be grown before it will settle',
  '305-階段の寸法': 'Two staircases can both satisfy the stride rule of twice the rise plus the going equalling 610mm and still differ by twenty degrees of pitch — the formula only asks whether the step matches a stride, never how steep the climb is, and at the legal limit you cannot see the treads on the way down',
  '339-モールス符号': 'Nothing about the shape of a dot or a dash is fixed; what is fixed is the ratio of durations — dash three, gap inside a letter one, between letters three, between words seven. That is why the same code carries over sound, light or a key. Laid out at true length, SOS comes to exactly 27 units.',
  '304-QRコードの作り': 'A QR code can be 21 modules across or 177, but the three finder squares stay 7 by 7 whatever the version — the thing you have to find first is always the same size, and its 1:1:3:1:1 run of black and white reads the same scanned sideways or diagonally, so orientation never has to be known in advance',
  '303-ISBNの作り': 'Only the middle two fields of an ISBN change length, so a publisher that issues many books holds a short registrant number and gets a longer title field in return — and the check digit, a weighted sum of alternating 1s and 3s, is deliberately imperfect: swapping two adjacent digits that differ by five slips straight through',
  '302-道路標識': 'You know what kind of sign it is before you can read a word of it: shape and colour arrive first, so a yellow diamond means caution from further away than any text can be resolved — and the main sign carries no conditions at all, since when and where and to whom it applies lives on the small plate below it',
  '319-被害認定の区分と支援': 'Japan grades earthquake and flood damage to a house on a single scale of economic loss, and the six names on it are just intervals: under 10% is partial, then four ten-point bands, and everything from 50% upward is simply "total". The cuts are where public help begins rather than where the damage looks different, which is why two of them were added only in 2020 and 2021.',
  '318-処方箋の読み方': 'A Japanese prescription form, laid out box by box, with one line of it taken apart: drug name, how much is in one packet, how many packets per dose, how many times a day and when, and how many days it covers — all five in a single line. The form also has to say how long it stays valid, and when that box is left blank the default is four days counted from the day it was issued, holidays included.',
  '301-治験の三つの相': 'The phases of a clinical trial are not divided by how many people take part but by who they are — healthy volunteers, then a few mildly affected patients, then the people who would actually use the drug — and only the last of the three is described as verifying efficacy rather than examining it',
  '300-日本の硬貨': 'Three orderings that never agree: the 50 yen coin is smaller than the 5, the 10 is bigger than the 100, and the weights rank differently again — the only two with holes are the 5 and the 50, which are then told apart by the milled edge, because the set is designed to be read by hand',
  '299-本が読者に届くまで': 'Bookshops in Japan never bought the books on their shelves: the trade runs on consignment, so unsold copies travel back up the same chain, and the wholesaler in the middle is really a bank — paying publishers in advance against sales that have not happened and deferring collection from the shops',
  '298-交通信号機': 'Green sits at the end of the row because red has to sit where it is most visible: the order of the colours is not an aesthetic choice but a ranking of how badly each one would be missed — and the arrows below follow the same logic, left turn under green, straight under amber, right turn under red',
  '297-郵便物の規格': 'Standard mail is not a size of envelope but the name of four conditions met together — length, width, thickness and weight — and breaking any one of them moves the item to a different price table entirely; the 1cm thickness limit is really the line between what a sorting machine can swallow and what it cannot',
  '296-献血から輸血まで': 'One donation splits into three products that keep for wildly different times — red cells 28 days cold, plasma a year frozen, platelets just four days at room temperature — which is why plasma can be stockpiled and platelets cannot, and why the shortage people talk about is almost always the four-day one',
  '295-土俵': 'Four of the sixteen bales that make the 4.55m ring are pushed one bale-width outwards, so a wrestler whose heel lands there is still in — and the sand raked around the outside is not decoration but the instrument of judgement, since a foot that left the ring leaves a print',
  '294-能舞台': 'Which way the floorboards run is what separates one area from another: the chorus sits where the boards run lengthwise like the main stage, the musicians where they run crosswise — and the four pillars are not decoration but the only way a masked actor, who can see almost nothing, knows where he is standing',
  '293-立体構造を決めるまで': 'Diffraction records only intensities, never phases, so a crystallographer has to fetch the phases from somewhere else — a known structure, anomalous scattering, or a heavy-atom derivative — whereas cryo-EM has no phase problem at all and pays instead by having to average tens of thousands of particles',
  '292-製麹の品温': 'Growing koji is two days of walking a temperature up and stopping it at the top: the mould heats itself as it grows, so the maker cannot hold the temperature down — only decide how often to break the rice up, and the shape of that climb is the recipe',
  '291-たんぱく質のトポロジー図': 'Throw away every length and only the fold is left: a TOPS cartoon draws helices as circles and strands as triangles, and whether a connecting line stops at the edge of a symbol or runs into its centre is what tells you which end of the strand it joins — so two proteins of very different size can share one diagram',
  '290-ラマチャンドランプロット': 'Two angles per residue are almost the whole story of a protein backbone: the peptide bond is a partial double bond so omega barely turns, leaving phi and psi, and each secondary structure lands in its own patch of the plot — which is why structure validation is done on six separate plots, since glycine and proline are allowed quite different places',
  '289-自転車ホイールの組み方': 'A spoke pattern is named after how it crosses, not how it connects: three crossings per spoke is a 3-cross, also called six-spoke because the sixth spoke counted from the reference is the one it meets, and the half-pitch offset between the two hub flanges is what separates JIS lacing from Italian',
  '288-茶室の四畳半と八炉': 'The mats decide the room, not the other way round: a 4.5-mat tea room is a square of exactly three mat-widths with four mats pinwheeled around a half mat, and where the sunken hearth is cut — inside the host mat or outside it, in either handedness — gives the eight hearth positions that each change the procedure itself',
  '287-日本酒の三段仕込み': 'Sake is the rare brew where starch is turned to sugar and sugar to alcohol in the same tank at the same time, so the rice is added in three goes over four days — one sixth, then two, then three — because pouring it all in at once would dilute the lactic acid that keeps the starter safe',
  '286-魚の三枚おろし': 'Which way the knife travels is decided by the backbone, not by the cook: the belly side is cut head to tail and the back side tail to head, and a cross-section shows the two cuts running either side of the bone to leave three pieces — right fillet, left fillet, bone',
  '285-車いすの基本寸法': 'Passing through and turning around are different problems: a 700mm chair clears an 800mm door but needs a 1,400mm square to turn 180 degrees and a 1,500mm circle to turn right round',
  '259-家具の転倒防止': 'Mass cancels out of the tipping condition, so how easily furniture falls depends only on its depth and the height of its centre of gravity — a shallow tall bookcase goes over at a shindo 5+',
  '258-液晶テレビの層': 'An LCD makes no light of its own — it only blocks it, which is why its black is whatever light failed to be blocked, and why only a tenth of the backlight ever reaches your eye',
  '257-換気扇の風量と静圧': 'The airflow on the box is the free-delivery figure; what you actually get is where the fan curve meets the duct resistance, and a long bent duct can cut it to 43 percent',
  '256-食洗機の水の道': 'A dishwasher does not use less water, it uses the same water many times: 10 litres pumped around twenty times is 200 litres of water hitting the dishes',
  '255-炊飯器の温度と圧力': 'Boiling water refuses to go past 100C, so a pressure cooker adds exactly one part — a valve — to lift that ceiling to about 105C',
  '254-給湯器の号数': 'A water heater is rated in heat, not flow: the same 24-go unit gives 40 litres a minute in summer and 17 in winter, because the rating assumes a 25 degree rise',
  '253-引き出しのスライドレール': 'The slide decides the drawer, not the other way round: a side-mounted pair takes 12.7mm each side, so a 500mm opening leaves a 474.6mm box',
  '252-サイクロン掃除機の分け方': 'Centrifugal force is v squared over r, so a tenth of the radius is ten times the g — but a tenth of the radius is a hundredth of the airflow, which is why the small cones come in rows',
  '251-IHの原理': 'Induction heats only the outer 0.05mm of the pan, and that thin skin is why iron works and aluminium does not: at 20kHz iron\'s surface resistance is 43 times aluminium\'s',
  '250-ドラム式洗濯機の構造': 'The same drum has to stay under 1G to wash and reach 335G to spin, which is why it hangs on springs behind a concrete weight rather than being bolted to the machine',
  '249-棚板のたわみ': 'A shelf sags with the cube of its span, so doubling the span sags it eight times — and gluing a 40mm rail under the front edge does more than upgrading the board',
  '248-電子レンジの構造': 'Hot and cold spots sit 6.1cm apart because that is half of the 12.2cm wavelength, which no cabinet design can remove — so the food is moved instead',
  '247-エアコンの四方弁': 'Heating and cooling swap the roles of the indoor and outdoor coils, and the only part that changes is one valve — which is also why a heat pump briefly runs cooling in the middle of heating, to melt its own frost',
  '246-冷蔵庫の中身': 'A fridge does not make cold, it pumps heat out — and it throws away more than it took, because the compressor\'s electricity comes out as heat too',
  '245-エスカレーターの構造': 'The tread is always horizontal: the staircase appears because the front and rear rollers run on separate rails, and where those two rails come together the steps flatten out at the landing',
  '244-エレベーターの構造': 'The counterweight is not there to cancel the weight but to halve the difference: car plus half the rated load, so the motor only ever lifts half the rated load in either direction',
  '333-歯車のかみ合い': 'What sets the size of a gear tooth is the module, not the diameter — the diameter is what comes out of it, and so is the centre distance, which means the shaft positions are fixed the moment the gears are chosen. Two gears mesh if the module and the pressure angle match; the tooth counts and diameters can differ freely, and the speed ratio is just the inverse ratio of the tooth counts.',
  '243-はめあい': 'The same 30mm turns into a running fit or a permanent one depending on two letters: H7/g6 leaves 7 to 41 microns of clearance, H7/p6 always bites by at least 1 micron',
  '242-溶接記号': 'A welding symbol is read together with its arrow: below the reference line means the arrow side, above it means the other side, so the same symbol welds the opposite face if the arrow moves',
  '241-データセンターの電力系統': '2N does not mean doubling: it means two paths that never join before the equipment, because one shared point is a single point of failure — and the UPS is not a power source, just the bridge over the 10 seconds the generator needs',
  '240-地の目とバイアス': 'Cloth stretches on the 45 degree bias because nothing stretches: the woven square shears into a rhombus, so at a 120 degree cell the length gains 22.5 percent while the width loses 29.3 percent — it narrows more than it lengthens',
  '239-縫い方の番号': 'Stitches are specified by number, not by name: 301 rather than "lockstitch" — three digits for the stitch, five for the seam, and the two standards are separate because thread and cloth are decided separately',
  '238-板金の展開図': 'A flat pattern is not the sum of the outside dimensions: the outside stretches when you bend it, and the amount subtracted is each shop measured value, not a standard',
  '237-基板の層構成': 'Adding layers is not only about routing: it brings the ground plane close, and the same 50 ohms goes from a 2.85mm trace to a 0.34mm one',
  '236-PoEの給電クラス': 'A PoE standard quotes two wattages, not one: what the switch sends and what the device receives — the difference is what the 100m of copper turns into heat',
  '330-データセンターの気流': 'If every rack faces the same way, each row breathes in the exhaust of the row in front. Turning alternate rows around creates a cold aisle between the fronts and a hot aisle between the backs, so cold air rises through floor grilles into the fronts and hot air leaves the backs for the ceiling. Air cooling tops out around 15kW a rack, and PUE of 1.0 is the theoretical floor.',
  '326-半導体ができるまで': 'It looks like one line of work, but the three steps in the middle — deposit a film, print a pattern with light, etch away what is not wanted — run once per layer, and there are many layers. Everything up to the wafer test is the front end; after that the wafer is cut into chips, mounted, sealed against shock and moisture, and tested again.',
  '325-ハブとスイッチとアクセスポイント': 'Wire the same four machines three ways, send one frame from A to B, and the difference is how far it travels: a repeater hub copies it to every other port, a switch sends it only to the port it has learned B is on, and over the air everyone in range receives it. The dashed outlines are collision domains, and only the switch cuts them apart.',
  '324-LANケーブルの結線': 'There are two wiring standards for an eight-pin Ethernet plug and they differ in only four wires: T568A and T568B swap the orange pair with the green pair, while pins 4, 5, 7 and 8 are identical. Pair 3 is split across pins 3 and 6 with pair 1 sitting between them, a layout inherited from telephone wiring, and gigabit uses all four pairs rather than two.',
  '235-19インチラックと1U': 'Rack holes are deliberately unevenly spaced — 15.875 / 15.875 / 12.7 — so that the middle of the 12.7 gap marks where one U ends and the next begins',
  '320-TCPのつなぎ方と切り方': 'Opening a TCP connection takes three segments and closing it takes four, and the extra one is the whole point: "I have nothing more to send" and "I will not receive any more" are separate statements, so between the two FINs one side is still allowed to send. The eleven RFC 793 states are listed beside the ladder, along with why the last side to send an ACK has to wait before it disappears.',
  '234-プロトコルのヘッダ': 'Protocol headers are drawn 32 bits wide because that is the unit they are read in: the width of a field is its bit count, and nothing that does not divide into 32 ever appears',
  '322-分子の形とVSEPR': 'Electron pairs around a central atom push each other as far apart as they can, and that alone fixes the shape. Methane, ammonia and water all have four pairs on the same tetrahedral skeleton; what differs is how many of them are bonds, and each lone pair squeezes the bond angle further — 109.5, then 107, then 104.5 degrees.',
  '233-周期表の形': 'The shape of the periodic table is the electron configuration: block widths of 2, 6, 10 and 14 are orbital capacities, so no other width is possible',
  '232-応急危険度判定': 'A red placard does not mean total loss: it answers whether it is safe to go in now, not how badly the building is damaged — two different papers, two different questions',
  '231-避難所の開設': 'Opening a shelter starts by checking whether the building itself survived — put people in first and you may have to move them again',
  '230-災害対策本部と報告の経路': 'Disaster headquarters: one chain of command and one place for information, and for the biggest events the report skips a rung and goes to prefecture and nation at once',
  '229-折丁と台割': 'Signatures and the page plan: collation marks step down the spine, so one signature out of order breaks the staircase — an inspection turned into a shape',
  '228-STARTトリアージ': 'START triage: four things to look at, three separate roads to red, and only two treatments allowed on the spot — because stopping costs the people behind',
  '227-三角定規と分度器': 'Two set squares come as a pair because two of them make ten angles in 15-degree steps, where one alone makes only four',
  '226-用途地域13種類': 'Thirteen zoning districts: the name alone fixes nothing — coverage and floor-area ratios are chosen from a list, and the same 200m² lot can hold eight times the floor area',
  '225-災害時のトイレ': 'Disaster toilets are counted in uses, not litres: five per person per day, so a family of four needs 140 bags for a week — and the bags stay in the house',
  '224-罹災証明の住家被害認定': 'Damage certification: a hazard map measures from the ground, this measures from the floor — so the same water gives two different numbers, and 0.1m changes the category',
  '336-航海灯': 'At night you see no hull, only coloured lights, so the arcs are cut to make the colours alone fix her heading. Each sidelight covers 112.5 degrees and the sternlight 135 — exactly 360 with no overlap. Green alone means she crosses to your right, red alone to your left, both means head on, and a white sternlight means you are overtaking.',
  '223-海図の読み方': 'A nautical chart carries three datums at once: depths from the lowest water, clearances from the highest, and light heights from the mean — each taken at its worst case',
  '222-平屋の保育園の避難計画': 'A single-storey nursery has no upstairs, so the plan is half about the building next door — and three people coming out to help halves the time the children spend outside',
  '331-緊急地震速報': 'An earthquake early warning does not predict anything; it borrows the gap between the fast P wave and the slow S wave. Three seconds of waveform are needed to size the quake and the processing takes seconds more, and those costs are the same however far away the epicentre is — so the warning time is only what is left over, and directly beneath a shallow quake there is nothing left.',
  '221-避難行動の判定と浸水深': 'Deciding whether to leave: five questions answered once, in advance — and flood-depth bands read as floors of your own house, not as metres',
  '220-防火区画と避難経路': 'Fire compartments: the shortcut you use every day is the one that closes — a drill map must show the route after the shutters come down, not before',
  '219-算数数学の問題図': 'Figures in maths problems: the marks carry the meaning — equal ticks, right-angle squares, parallel chevrons — and only the given values are written on the figure',
  '328-ゼーゲルコーン': 'A pyrometric cone is not a thermometer. It is a small clay pyramid stood at 8 degrees in the kiln, and it bends until its tip is level with the base — at which point the ware has had the right amount of heat work, meaning temperature and time together. The quoted temperatures hold only for a stated heating rate: the same cone bends at a different temperature if the kiln climbs faster.',
  '218-窯詰めの棚組み': 'Kiln loading: three posts per shelf, because three points always lie in one plane — and bisque and glaze firings are packed in opposite ways',
  '217-上部式フィルターの断面': 'Aquarium filter in section: it does not remove the poison, it turns it into a weaker one — and the water must meet the mechanical media before the biological',
  '216-日本の硬貨6種': 'Japanese coins: the order by size is not the order by value, so the hand reads the hole first, then the reeding, and only then the size',
  '215-NANDフラッシュの階層': 'NAND flash: reads and writes go by the page, erases only by the block — every other property of an SSD follows from that mismatch',
  '214-日影規制と等時間日影図': 'Shadow-hour zoning: the iso-shadow lines here were computed, not sketched — the inner line clears its limit but the outer one does not',
  '213-血球計算盤の目盛り': 'Haemocytometer grid: the 0.100mm depth is what turns an area into a volume, so one 1mm square holds exactly 0.1 microlitres',
  '212-割物花火の断面': 'Aerial shell in section: the stars keep their relative positions as they fly, so how they are packed is the shape you see',
  '211-N値計算と接合金物': 'Hold-down selection (N-value method): the stronger a shear wall is, the harder it pulls its end post out of the ground',
  '210-楽譜の寸法': 'Music engraving: the staff space is the unit for every measurement, and the stem is 3.5 of them',
  '209-コンパスと定規の作図': 'Ruler-and-compass constructions: no scale is used, because equal compass openings make equal lengths',
  '208-建蔽率と容積率': 'Floor-area ratio in Japan: a narrow street caps it below the zoned figure, so the road sizes the building',
  '207-ウェハのダイ取り': 'Die-per-wafer: squares in a circle, so the bigger the die the larger the share thrown away',
  '206-ピアノのアクション': 'A piano action: the jack lets go just before the string, so nothing is pushing the hammer at impact',
  '327-マイクの指向性': 'A polar plot of how much a microphone picks up from each direction. The three familiar shapes are not separate inventions but one formula at its ends and middle — omnidirectional, cardioid and figure-of-eight are A = 1, 0.5 and 0 in r = A + (1 - A)cos θ. Solving the same formula gives the dead angles: 180 degrees for a cardioid, 90 and 270 for a figure-of-eight.',
  '205-ホールの初期反射': 'Hall acoustics: delay is nothing but a difference in path length \u2014 one millisecond is 0.34 m',
  '204-ギターのフレット位置': 'Guitar frets are a geometric series, and the saddle must still be moved back to play in tune',
  '203-壁量計算と4分割法': 'Japanese timber wall-quantity check: enough shear wall still fails if it sits on one side',
  '202-斜線制限': 'Japanese setback planes: the shape of a house is decided by slanting lines, not by the plot',
  '201-椅子の製作図': 'A chair drawn for making: four tenons meet in the back leg, and they must be set at different heights',
  '200-作業机の製作図': 'A bench built for making: tenons mitred where they meet, and a top that is never screwed down',
  '199-日本銀行券の識別マーク': 'Banknote tactile marks: the shape is identical, and only its position tells the denomination',
  '198-ミツバチの巣房': 'Honeycomb cells: for a given area the hexagon has the shortest wall of any shape that tiles',
  '197-等角図と三面図': 'Isometric, third-angle and oblique: one scale serves all three axes, but circles become ellipses',
  '196-勾配の書き方': 'Slope notation: roofs in sun, ramps in fractions, roads in percent, railways in per mille \u2014 degrees are the minority',
  '195-学校の机と椅子': 'School desks and chairs are sized by height, not by year, and the pair must match',
  '194-点字の6点': 'Braille has only six dots, so \u201ca\u201d and \u201c1\u201d are the same shape until a number sign says otherwise',
  '193-カードの版面': 'A trading card layout: the back must look the same upside down, or the face is readable from the table',
  '192-サッカーボールの形': 'A football is a truncated icosahedron: the 12 degrees missing at every vertex are what make it a sphere',
  '337-露出とEV': 'Brightness is set not by the aperture or the shutter but by their sum, so equal exposures line up on a diagonal: f/2.8 at 1/500, f/4 at 1/250 and f/5.6 at 1/125 are all 12 EV. One stop either way halves the light. What the diagonal does not equalise is the picture — a smaller aperture deepens the focus and a slower shutter lets movement blur, which is why choosing along it is the craft.',
  '191-凸レンズの作図': 'Ray tracing through a convex lens: there are only three lines to draw, and two of them fix the image',
  '190-中綴じの面付け': 'Saddle-stitch imposition: facing page numbers always add up to the page count plus one',
  '189-点字ブロック': 'Tactile paving: only two kinds, and one line tells you which side the platform is on',
  '188-裁判員裁判の法廷': 'A lay-judge courtroom: the prosecution sits on the bench\u2019s right, so on the plan it is on the left',
  '187-合板の木取り図': 'A plywood cutting diagram: enough area is not the same as a way to cut it',
  '186-冷蔵庫の据付と搬入': 'Fitting a refrigerator: clearances differ by model, and a corner turns on the diagonal',
  '185-地上天気図の読み方': 'A surface chart: the barbs tell you which way the front is moving',
  '184-本会議場の議席配置': 'A debating chamber: the seating order itself states how large each bloc is',
  '183-台風の進路予想図': 'A typhoon forecast: the circle is where the centre lands 70% of the time',
  '182-公園の遊具と安全領域': 'Playground clearances: the fall height decides how much space to keep',
  '181-伽藍配置の移り変わり': 'Temple layouts through time: the pagoda drifts away from the centre',
  '180-継手と仕口': 'Japanese timber joints: pulled harder, they tighten; each post has a name',
  '179-革靴の型紙': 'A shoe pattern comes off the last: tape it, draw on it, peel it flat',
  '178-靴のサイズの図': 'Shoe sizing as a nomogram: 25.0 EE and 26.0 E are the same girth',
  '177-帽子の型紙': 'A hat pattern: a 12cm side wall unrolls into a fan of 50cm radius',
  '176-トートバッグの型紙と裁ち方図': 'A bag pattern: half of it is drawn, and the yardage falls out of the layout',
  '175-ペルシャ絨毯の意匠図': 'A Persian rug cartoon: one square is one knot, and only a quarter is drawn',
  '174-送電線路の縦断面図': 'A transmission line profile: the wire sags, and the towers are sized so it still clears',
  '173-販売図面-英語表記': 'The greyscale version of the same trade: walls as mass, no loose furniture',
  '166-マンションの販売図面': 'An estate agent floor plan: made to decide with, not to build from',
  '165-地図記号の絵地図': 'Japanese map symbols: a circle around a sign makes it the senior one',
  '164-小学校の回路図': 'The circuit diagram taught at primary school: series and parallel',
  '163-Residential-duct-layout': 'Ducts are sized by a pressure budget, not by the room',
  '162-Cabin-LOPA': 'The seat count is not what fits - it is what the exits allow',
  '161-Weaving-draft': 'Three small grids decide the fourth - the cloth is computed',
  '160-Change-ringing-method': 'A method is not a tune - it is a path through a grid',
  '159-Fire-IAP-map': 'Not a picture of the fire - the way out is written on it',
  '157-Drill-chart': 'No dimensions on it - the field is the ruler',
  '156-Metes-and-bounds-plat': 'A deed describes land as a walk, not a picture',
  '155-Lane-closure-plan': 'A lane closure is mostly road, not work: the taper, the buffer and the termination area take far more length than the job itself',
  '154-Fire-alarm-plan': 'Fire alarm devices: spacing is a circle, not a square',
  '145-Sprinkler-layout': 'Sprinkler layout: area per head and spacing, decided together',
  '33-駐車場の区画割': 'A surface car park set out for fourteen cars, with bay dimensions, aisle width and where the entrance and exit sit',
  '152-Septic-site-plan': 'Septic site plan: a plan decided by how fast water leaves the soil',
  '147-Site-plan-setbacks': 'Site plan: the envelope is the lot with the yards taken out',
  '30-総合仮設計画図': 'Site logistics plan with the crane radius',
  '138-ロープ高所作業の作業計画図': 'Rope access work plan — the law says what the drawing must carry',
  '51-工事工程表': 'A construction bar chart with a bar per trade, showing where the work overlaps and where the labour piles up',
  '42-擁壁の標準断面図': 'A standard section through an L-shaped retaining wall: the body dimensions, the reinforcement, and the crushed stone, backfill, weep holes and drainage',
  '43-舗装構成の断面図': 'A road pavement section stacking surface, binder, upper and lower base courses and subgrade, each with its thickness',
  '114-点字ブロックの敷設図': 'Tactile paving: bars mean go, dots mean stop',
  '28-ダムの平面図': 'The plan of a concrete gravity dam: the body, the spillway, the intake works and the access road for maintenance',
  '27-圃場整備の平面図': 'A farmland consolidation plan laying out 30-are plots, with the irrigation channels, the drainage channels and the farm roads that serve them',
  '62-寺院庭園の平面図': 'Temple garden plan, drawn with closed curves',
  '41-露地の平面図': 'The garden path to a tea house: outer and inner roji, with the stepping stones, water basin, middle gate, waiting bench and planting',

  // 設備・電気
  '18-配管の系統': 'A cooling water P&ID where pumps, heat exchangers, valves and instruments are joined by pipes distinguished by line type',
  '38-計装ループ図': 'An instrument loop from sensing element through transmitter and controller to final element, every device carrying its ISA tag',
  '19-受変電の結線': 'A substation single-line diagram from the incoming supply through disconnector, breaker and transformer to the low voltage boards',
  '142-Panel-schedule': 'Panel schedule: the table is shaped like the panel',
  '50-電子回路図': 'An LED circuit drawn with IEC and JIS symbols: supply, resistor, LED and switch',
  '06-家の電気系統': 'A house wiring layout from the service entrance to the consumer unit, then breaker by breaker to the sockets and lights in each room',
  '10-給排水の系統': 'The four plumbing systems of a house — cold supply, hot supply, drainage and venting — separated out fixture by fixture',
  '103-陸上養殖の循環系統図': 'Land-based aquaculture: the water is cleaned, not replaced',
  '321-下水処理の流れ': 'A sewage works does not destroy the dirt; it feeds it to microorganisms, settles them out and carts them somewhere else. One line in the drawing runs backwards — the returned sludge, because the microorganisms are the machine, so they are put back rather than thrown away, and only the surplus is drawn off into the sludge line. A combined sewer also spills untreated water in heavy rain.',
  '35-配水系統図': 'A town water distribution network from treatment works through service reservoirs and trunk mains to each supply zone, with the ground level of every zone',
  '44-人工衛星の系統図': 'The subsystems of a 150kg satellite and how they connect: power, communications, attitude control, data handling and the mission payload',

  // 医療・食品・農
  '72-歯周チャート': 'A periodontal chart where all 32 teeth are measured at six points each, recording pocket depth, bleeding and mobility',
  '146-Restorative-chart': 'Restorative chart: one number fixes a tooth',
  '39-経絡と経穴': 'The fourteen meridians and their principal points, named to the WHO standard acupuncture point locations',
  '36-手術室の機器配置': 'An operating room laid out around the table: surgical light, anaesthesia machine, electrosurgical unit and monitors, with the sterile field',
  '09-患者の動線': 'How an outpatient moves through a hospital — reception, consultation, tests, payment, prescription — and where each department keeps people waiting',
  '108-おせち重箱の詰め方': 'A new year box packed in odd numbers and with no gaps left, in three of the traditional arrangements',
  '104-牛枝肉の部分肉分割図': 'Beef cutting chart: the bones decide the lines',
  '23-厨房の動線': 'A school meal kitchen split into contaminated and clean zones, with the paths of food, people and crockery kept from crossing',
  '115-食品工場のアレルゲン動線図': 'Allergen flow: never let the path double back',
  '135-工業用パターン': 'Industrial pattern: cloth cannot be uncut',
  '100-裁ち合わせ図': 'Cutting layout: the pattern may not be turned',
  '40-弁当の盛付図': 'A packing instruction for a boxed lunch: what goes in each compartment, how much, which way up, and in what order',
  '94-ヘアカラーのブロッキング図': 'Hair colour sectioning: the order is the content',
  '92-防虫モニタリングの定点配置図': 'Pest monitoring: the stations never move',
  '91-リンゴ高密植栽培の樹形図': 'High-density apple training, with tree and row spacing',
  '125-庭木の剪定指示図': 'Pruning instructions: not which branch, but where to cut it',
  '131-刺網の網図': 'Gill net: the mesh opens because the net is hung short',
  '105-養蜂の巣枠配置図': 'Hive frames: reorder them and the brood goes cold',
  '73-サビキ仕掛け図': 'A sabiki fishing rig from main line to six hooks, feeder cage and sinker, with the gauge and length specified for every section',

  // 店舗・物流
  '15-店舗のレイアウト': 'A convenience store floor layout: the fixtures, the main aisle, the till and chilled cases, and the path a customer takes from the door',
  '58-商店街の店舗案内図': 'Shopping street directory, trade by hatch',
  '59-フードコートの配置図': 'A food court laid out with 240 seats in the middle and the outlets around the edge, each cuisine distinguished by hatch rather than colour',
  '109-ヤーデージブック': 'Yardage book: shade the surfaces, write the distances',
  '60-ドームの座席等級図': 'A domed stadium with its seats divided into five price bands, including standing room',
  '150-Baseball-infield': 'Baseball infield: every distance starts at the apex of home plate',
  '97-防犯カメラの視野図': 'Camera coverage, out to the distance a face still reads',
  '153-Parking-striping': 'Parking striping: the access aisle is not spare tarmac',
  '34-倉庫のロケーション': 'A warehouse where every rack bay, level and position carries an address, overlaid with the aisles and the picking route',
  '149-Pallet-rack-layout': 'Pallet rack: the truck decides the aisle',
  '116-引越しの搬入経路図': 'Moving route: the drawing that says whether it fits',
  '98-パレット積付図': 'Pallet patterns, and what they do to stability',
  '132-クレーン揚重計画図': 'Crane lift plan: the further out, the less it lifts',
  '120-トラックの積載計画図': 'Truck loading: weight times distance from the axle',
  '89-コンテナ船の積付図': 'Container stowage: bay, row and tier are the address',
  '126-船の一般配置図': 'General arrangement: four drawings, each with its own scale',
  '12-在庫と発注': 'How a shop restocks: the reorder point, the safety stock, and the lead time that has to be covered until goods arrive',
  '332-振込が届くまで': 'Money and the notice of it do not travel together, and which one goes first flips at a hundred million yen. Below that, the notice reaches the receiving bank at once while the banks settle only the netted difference at a quarter past four; above it, each transfer is settled gross and in real time before the notice is sent. The two paths cross on the page because the order really does cross over.',
  '329-ごみが行く先': 'Incineration is not a way of making rubbish vanish; it is a way of cutting its volume by 80 to 95 per cent, and the ash still has to go to landfill. Whether a municipality or the business that produced it is responsible depends not on what the waste is but on where it came from — the same paper is household waste at home and industrial waste at an office.',
  '338-石油が製品に分かれるまで': 'Distillation only separates what the crude already contains, and it yields fewer light fractions than the market wants — so the heavy ends get broken up to make more. Vacuum distillation squeezes further gas oil from the residue, then cracking units cut the big molecules down, and only after desulphurising and reforming is any of it a product.',
  '323-鉄ができるまで': 'Half of ironmaking is putting carbon in and the other half is taking it back out: the blast furnace uses carbon to strip the oxygen off the ore and leaves molten iron at around 4% carbon, which is hard but shatters, so the converter blows it down below 2% to make steel. The scrap route skips the ore, the furnace and the coke entirely.',
  '08-工場のライン': 'An assembly line with what happens at each station, and the route a part takes back when inspection rejects it',

  // 業務・組織
  '20-組織図': 'A company organisation chart down to section level, with headcount and remit written on each box',
  '07-承認の流れ': 'The route a written proposal takes through each rank of approval, including the conditions that send it back',
  '05-業務の流れ': 'From order to shipment: credit check, stock allocation, picking instruction, packing and despatch, with the owner of each step',
  '11-取材から公開まで': 'How an article gets made — commissioning, interview, writing, subediting, typesetting, publication — and the loops back when it is sent for rework',
  '13-学校の年間': 'The path from application to enrolment — examination, results, admission procedures — with the deadline on every step',
  '55-学校の時間割': 'A lower secondary school week: periods down the side, days across the top, and the subject, room and teacher in each cell',
  '31-座席図': 'Seating plan, sixty seats and two wheelchair spaces',
  '107-葬儀式場の配置図': 'Funeral hall: the seating is the order of offering',
  '113-墓石の彫刻指示図': 'Gravestone engraving: the living are cut in red',
  '16-会場の配置': 'An exhibition hall divided into booths, with aisle widths and the position of reception, meeting space and the goods entrance',
  '130-法定相続情報一覧図': 'Statutory heir chart: the bottom 5 cm is left for the registry stamp',
  '133-投票所の配置図': 'Polling station: three ballots, so nobody may double back',
  '99-法廷の配置図': 'Courtroom: where you sit is what you are',
  '64-施設の開館表': 'A sports hall opened by the week: time bands per day allocated between clubs, groups and individual use',
  '65-ビンゴ大会の進行表': 'A running order for a bingo night with who does what at each time, plus the floor plan of the prize desk and the queue for checking cards',
  '84-中古車の査定図': 'Used car appraisal: a body map and the deduction codes',
  '112-交通事故の現場見取図': 'Collision scene: every dimension from one datum',
  '90-相続関係説明図': 'Family tree for probate: marriage doubled, descent single',
  '118-特許図面の書き方': 'Patent drawings have rules of their own: line weights, margins, how reference numerals are attached and how figures are arranged',
  '122-円だけで作る動物のマーク': 'Four animal marks built from circles alone, where every sharp corner is the intersection of two of them',
  '123-アイコンのキーライン図': 'Icon keylines: what is matched is the size the eye sees',
  '129-家紋の割り出し': 'Laying out a family crest with compass divisions',
  '128-ロゴの作図': 'A real logo with no coordinates in the source (5.4 KB)',
  '127-ロゴのコンストラクション図': 'Logo construction from compass and straightedge',
  '124-和欧混植の寸法図': 'Mixing scripts: two typographies with different baselines',

  // 催し・遊び
  '96-オーケストラの配置図': 'Orchestra seating, two traditions side by side',
  '110-ダンスのフォーメーション図': 'Dance formations: the diagonal reads strongest',
  '77-舞台照明仕込図': 'Theatrical lighting plot, with the channel schedule',
  '137-舞台転換図': 'Scene change plot: what happens between the pictures',
  '117-カメラ配置図': 'Camera plan: cross the line and left becomes right',
  '101-PA配置図': 'PA layout, where distance turns into delay',
  '106-雑踏警備計画図': 'Crowd plan: how many can flow out against how many come in',
  '93-花火大会の保安距離図': 'Fireworks safety distances, a circle per shell size',
  '121-生け花の構成図': 'The three main stems of a formal ikebana arrangement, set by the ratio of their lengths and the angle each one leaves at',
  '66-囲碁の棋譜': 'A game record on a 19-line go board where each stone carries the number of the move, showing the shape of the opening',
  '67-将棋の局面図': 'The starting position of shogi on a nine by nine board, the two sides told apart by which way the pieces point',
  '68-チェスの局面図': 'The starting position of chess on an eight by eight board, with the file and rank coordinates marked',
  '70-リバーシの局面図': 'The opening position of reversi: four stones in the centre four squares, black and white alternating',
  '69-ビンゴカード': 'A bingo card, five by five with a free centre, where each column draws from its own range of numbers',

  // UI・画面設計
  '74-EC商品ページのUI構造': 'Product page structure, desktop against mobile',
  '76-管理画面のレスポンシブ構造': 'The same admin screen at desktop, tablet and mobile, where the sidebar turns into a drawer rather than simply shrinking',
  '88-レスポンシブLPのUI構造': 'Landing page where sections appear and disappear',
  '87-モバイルアプリのUI構造': 'A mobile app with five bottom navigation tabs, and what each tab holds and where it can go from there',
  '75-画面遷移とワイヤーフレーム': 'Screen flow with the wireframes drawn in',
  '85-Checkoutの画面遷移': 'Checkout flow, five steps and where errors return to',
  '86-CRUD管理画面の画面遷移': 'CRUD admin flow: delete goes through a confirmation',

  // IT・ソフトウェア
  '26-データセンターのラック': 'A server room where racks face each other to make hot and cold aisles, with the clearance of each aisle written in',
  '21-テーブルの関係': 'An order management ER diagram with primary and foreign keys, and the one-to-many relationships drawn as crow feet',
  '46-クラス図': 'A UML class diagram where inheritance, realisation, association and aggregation are told apart by line type and end symbol',
  '47-状態遷移図': 'A UML state machine with transitions, the events and guards that fire them, and the pseudostates that begin and end it',
  '48-ユースケース図': 'A UML use case diagram with the actors, the use cases, and the include and extend relationships between them',
  '49-アクティビティ図': 'A UML activity diagram from start to end, including decisions, merges and the fork and join of parallel work',
  '02-クラウド構成': 'A cloud architecture showing the VPC and its subnets, and where the load balancer, application, database and object store sit',
  '01-オンプレのサーバ構成': 'An on-premise server layout rack by rack, with the redundant power feeds and network links drawn as separate paths',
  '03-データの流れ': 'Where data goes from collection through transformation, storage and aggregation to display, and what kind of container holds it at each step',
  '04-ネットワーク構成': 'A network layout of the links and equipment between sites, with the address range carried by each segment',
};
